# Generated by Django 4.1.1 on 2022-12-12 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0004_alter_auction_winner"),
    ]

    operations = [
        migrations.RemoveField(model_name="auction", name="product",),
        migrations.AddField(
            model_name="product",
            name="auction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="system.auction",
            ),
        ),
    ]
