# Generated by Django 4.1.1 on 2022-12-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0006_bid_auction_bid_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="offer",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
